version = 0.1

[default.global.parameters]
stack_name = "ar-assets-fastapi-dev"

[default.build.parameters]
cached   = true
parallel = true

[default.deploy.parameters]
region            = "ap-south-1"
confirm_changeset = true
resolve_s3        = true
capabilities      = "CAPABILITY_IAM"
parameter_overrides = [
  "Environment=dev",
  "AssetBucketName=menu-assets-dev-833090513377",
  "CognitoRegion=ap-south-1",
  "CognitoUserPoolId=ap-south-1_SCyQ50etN",
  "CognitoClientId=7903hkujl9qeq67toemi5qrhes",
  "CfDomain=d2rw2kah485lhg.cloudfront.net",
  "LogLevel=INFO",
]
