version = 0.1

[default.global.parameters]
stack_name = "orders-fastapi-dev"
region = "ap-south-1"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
confirm_changeset = true
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = [
  "Environment=dev",
  "MenuTable=MenuTable-dev",
  "OrderTable=OrderTable-dev",
  "CognitoRegion=ap-south-1",
  "CognitoUserPoolId=ap-south-1_SCyQ50etN",
  "CognitoClientId=7903hkujl9qeq67toemi5qrhes",
  "StepArn=arn:aws:states:ap-south-1:833090513377:stateMachine:order-state-machine-dev",
  "NotificationsQueueUrl=https://sqs.ap-south-1.amazonaws.com/833090513377/notifications-queue-dev",
  "LogLevel=INFO",
  "SkipMenuValidation=true",
]
s3_prefix = "orders-fastapi-dev"
disable_rollback = true
image_repositories = []
